backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_library:
  name: cloudinary
  config:
    cloud_name: dwa5hefth
    api_key: 467964347927819
    multiple: true

# Uncomment below to enable drafts
publish_mode: editorial_workflow

media_folder: 'src/images/uploads' # Media files will be stored in the repo under src/images/uploads
public_folder: '/images/uploads' # The src attribute for uploaded media will begin with /images/uploads

collections:
  # Our gallery photoshoots
  - name: 'gallery' # Used in routes, e.g., /admin/collections/gallery
    label: 'Photoshoot' # Used in the UI
    folder: 'src/photoshoots' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Author',
          name: 'author',
          widget: 'string',
          default: 'Anonymous',
        }
      - { label: 'Summary', name: 'summary', widget: 'text' }
      - { label: 'Tags', name: 'tags', widget: 'list', default: ['post'] }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Gallery'
        name: 'galleryImages'
        widget: 'list'
        fields:
          - { label: 'Source', name: 'src', widget: 'image' }
          - { label: 'Alt Text', name: 'alt', widget: 'string' }
  # Our pages e.g. About
  - name: 'pages'
    label: 'Page'
    folder: 'src/pages'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Permalink', name: 'permalink', widget: 'string' }
      - label: 'Navigation' # https://www.11ty.dev/docs/plugins/navigation/
        name: 'eleventyNavigation'
        widget: 'object'
        fields:
          - { label: 'Key', name: 'key', widget: 'string' }
          - { label: 'Order', name: 'order', widget: 'number', default: 0 }
      - { label: 'Body', name: 'body', widget: 'markdown' }
